### ISSUE TITLE
Support recheck comments

### ISSUE THREAD

**Issue by paladox** [dburm/pg-test-result-plugin#2]
Sometimes you write a recheck comment then jenkins re verifies your change (which sometimes means changing it's vote from a -1 to a +1). Currently this plugin only searches for the first message (which would be the one that failed if jenkins -1 the latest patchset).

Could support for it to look at last to top be supported please? Or at least some how support this?

**Comment by dburm** [comment]
Need to reproduce, but as far as I can see, script parses all messages related to current patchset from old to new(need to check .filter()), so verdict from comment-added will replace verdict from patchset-created. However script keeps datetime in this case, it's really a bug.
